package aws

import (
	"context"

	opengovernance "github.com/opengovern/og-describer-aws/discovery/pkg/es"
	"github.com/turbot/steampipe-plugin-sdk/v5/grpc/proto"
	"github.com/turbot/steampipe-plugin-sdk/v5/plugin"
	"github.com/turbot/steampipe-plugin-sdk/v5/plugin/transform"
)

//// TABLE DEFINITION

func tableAwsGuardDutyThreatIntelSet(_ context.Context) *plugin.Table {
	return &plugin.Table{
		Name:        "aws_guardduty_threat_intel_set",
		Description: "AWS GuardDuty ThreatIntelSet",
		Get: &plugin.GetConfig{
			KeyColumns: plugin.AllColumns([]string{"detector_id", "threat_intel_set_id"}),
			IgnoreConfig: &plugin.IgnoreConfig{
				ShouldIgnoreErrorFunc: shouldIgnoreErrors([]string{"InvalidInputException", "BadRequestException"}),
			},
			Hydrate: opengovernance.GetGuardDutyThreatIntelSet,
		},
		List: &plugin.ListConfig{
			Hydrate: opengovernance.ListGuardDutyThreatIntelSet,
			KeyColumns: []*plugin.KeyColumn{
				{Name: "detector_id", Require: plugin.Optional},
			},
		},

		Columns: awsOgRegionalColumns([]*plugin.Column{
			{
				Name:        "name",
				Description: "A ThreatIntelSet name displayed in all findings that are generated by activity that involves IP addresses included in this ThreatIntelSet.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Description.ThreatIntelSet.Name")},
			{
				Name:        "threat_intel_set_id",
				Description: "The ID of the ThreatIntelSet.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Description.ThreatIntelSetID")},
			{
				Name:        "detector_id",
				Description: "The ID of the detector.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Description.DetectorId")},
			{
				Name:        "format",
				Description: "The format of the threatIntelSet.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Description.ThreatIntelSet.Format")},
			{
				Name:        "location",
				Description: "The URI of the file that contains the ThreatIntelSet.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Description.ThreatIntelSet.Location")},
			{
				Name:        "status",
				Description: "The status of threatIntelSet file uploaded.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Description.ThreatIntelSet.Status")},

			{
				Name:        "title",
				Description: resourceInterfaceDescription("title"),
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Description.ThreatIntelSet.Name")},
			{
				Name:        "tags",
				Description: resourceInterfaceDescription("tags"),
				Type:        proto.ColumnType_JSON,
				Transform:   transform.FromField("Description.ThreatIntelSet.Tags")},
			{
				Name:        "akas",
				Description: resourceInterfaceDescription("akas"),
				Type:        proto.ColumnType_JSON,
				Transform:   transform.FromField("ARN").Transform(arnToAkas)},
		}),
	}
}
