package aws

import (
	"context"

	opengovernance "github.com/opengovern/og-aws-describer-new/SDK/generated"

	"github.com/turbot/steampipe-plugin-sdk/v5/grpc/proto"
	"github.com/turbot/steampipe-plugin-sdk/v5/plugin"
	"github.com/turbot/steampipe-plugin-sdk/v5/plugin/transform"
)

//// TABLE DEFINITION

func tableAwsAPIGatewayV2Route(_ context.Context) *plugin.Table {
	return &plugin.Table{
		Name:        "aws_api_gatewayv2_route",
		Description: "AWS API Gateway Version 2 Route",
		Get: &plugin.GetConfig{
			KeyColumns: plugin.AllColumns([]string{"route_id", "api_id"}),
			IgnoreConfig: &plugin.IgnoreConfig{
				ShouldIgnoreErrorFunc: shouldIgnoreErrors([]string{"NotFoundException"}),
			},
			Hydrate: opengovernance.GetApiGatewayV2Route,
		},
		List: &plugin.ListConfig{
			Hydrate: opengovernance.ListApiGatewayV2Route,
		},
		Columns: awsKaytuRegionalColumns([]*plugin.Column{
			{
				Name:        "route_key",
				Description: "The route key for the route.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Description.Route.RouteKey"),
			},
			{
				Name:        "api_id",
				Description: "Represents the identifier of an API.",
				Type:        proto.ColumnType_STRING,
			},
			{
				Name:        "route_id",
				Description: "The route ID.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Description.Route.RouteId"),
			},
			{
				Name:        "api_gateway_managed",
				Description: "Specifies whether a route is managed by API Gateway.",
				Type:        proto.ColumnType_BOOL,
				Transform:   transform.FromField("Description.Route.ApiGatewayManaged"),
			},
			{
				Name:        "api_key_required",
				Description: "Specifies whether an API key is required for this route. Supported only for WebSocket APIs.",
				Type:        proto.ColumnType_BOOL,
				Transform:   transform.FromField("Description.Route.ApiKeyRequired"),
			},
			{
				Name:        "authorization_type",
				Description: "The authorization type for the route. For WebSocket APIs, valid values are NONE for open access, AWS_IAM for using AWS IAM permissions, and CUSTOM for using a Lambda authorizer For HTTP APIs, valid values are NONE for open access, JWT for using JSON Web Tokens, AWS_IAM for using AWS IAM permissions, and CUSTOM for using a Lambda authorizer.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Description.Route.AuthorizationType"),
			},
			{
				Name:        "authorizer_id",
				Description: "The identifier of the Authorizer resource to be associated with this route. The authorizer identifier is generated by API Gateway when you created the authorizer.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Description.Route.AuthorizerId"),
			},
			{
				Name:        "model_selection_expression",
				Description: "The model selection expression for the route. Supported only for WebSocket APIs.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Description.Route.ModelSelectionExpression"),
			},
			{
				Name:        "operation_name",
				Description: "The operation name for the route.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Description.Route.OperationName"),
			},
			{
				Name:        "route_response_selection_expression",
				Description: "The route response selection expression for the route. Supported only for WebSocket APIs.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Description.Route.RouteResponseSelectionExpression"),
			},
			{
				Name:        "target",
				Description: "The target for the route.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Description.Route.Target"),
			},
			{
				Name:        "authorization_scopes",
				Description: "A list of authorization scopes configured on a route. The scopes are used with a JWT authorizer to authorize the method invocation. The authorization works by matching the route scopes against the scopes parsed from the access token in the incoming request. The method invocation is authorized if any route scope matches a claimed scope in the access token. Otherwise, the invocation is not authorized. When the route scope is configured, the client must provide an access token instead of an identity token for authorization purposes.",
				Type:        proto.ColumnType_JSON,
				Transform:   transform.FromField("Description.Route.AuthorizationScopes"),
			},
			{
				Name:        "request_models",
				Description: "The request models for the route. Supported only for WebSocket APIs.",
				Type:        proto.ColumnType_JSON,
				Transform:   transform.FromField("Description.Route.RequestModels"),
			},
			{
				Name:        "request_parameters",
				Description: "The request parameters for the route. Supported only for WebSocket APIs.",
				Type:        proto.ColumnType_JSON,
				Transform:   transform.FromField("Description.Route.RequestParameters"),
			},

			// Steampipe standard columns
			{
				Name:        "title",
				Description: resourceInterfaceDescription("title"),
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("Description.Route.RouteId"),
			},
			{
				Name:        "akas",
				Description: resourceInterfaceDescription("akas"),
				Type:        proto.ColumnType_JSON,
				Transform:   transform.FromField("ARN").Transform(arnToAkas),
			},
		}),
	}
}
